//using FL.Battle.Components;
//using System;
//using UnityEngine;

//namespace FL.Battle
//{
//    /// <summary>
//    /// 技能特效信息
//    /// </summary>
//    [Serializable]
//    public sealed class SkillVfxInfo
//    {
//        public enum EVfxTriggerType : byte
//        {
//            None = 0,
//            HitTarget,
//            ReachArea,
//        }
//        [Serializable]
//        public struct VfxInfo
//        {
//            [Header("特效名字")]
//            public string name;
//            [Header("特效持续时长，单位: 毫秒")]
//            public int duration;
//            [Header("特效延迟时长，单位: 毫秒")]
//            public int delay;
//        }
//        [Header("技能编号")]
//        [SerializeField]
//        private int _skillId;
//        [Header("施法特效")]
//        [SerializeField]
//        private VfxInfo _castVfx;
//        [Header("受击特效")]
//        [SerializeField]
//        private VfxInfo _hitVfx;
//        [Header("伤害计算延时 单位:毫秒")]
//        [SerializeField]
//        private int _damageDelay;
//        ///// <summary>
//        ///// 伤害范围
//        ///// TODO: 单体、圆形、矩形
//        ///// </summary>
//        //public Vector3 damageRange;
//        [Header("技能动作")]
//        [SerializeField]
//        private EAnimationName _animationName;
//        [Header("动作延迟 单位:毫秒")]
//        [SerializeField]
//        private int _animationDelay;

//        /// <summary>
//        /// 技能编号
//        /// </summary>
//        public int SkillId => _skillId;
//        public string CastVfxName => _castVfx.name;
//        public int CastVfxDuration => _castVfx.duration;
//        public int CastVfxDelay => _castVfx.delay;
//        public string HitVfxName => _hitVfx.name;
//        public int HitVfxDuration => _hitVfx.duration;
//        public int HitVfxDelay => _hitVfx.delay;
//        public int DamageDelay => _damageDelay;
//        public EAnimationName AnimationName => _animationName;
//        public int AnimationDelay => _animationDelay;
//        public SkillVfxInfo()
//        {
//            _castVfx.duration = 1000;
//            _hitVfx.duration = 2000;
//            _hitVfx.delay = 300;
//            _damageDelay = 300;
//            _animationName = EAnimationName.skill;
//        }
//    }
//}
