using UnityEngine;
using XGame.Framework.ObjectCollection;

namespace XGame.Framework.Map
{
    [DisallowMultipleComponent]
    [AddComponentMenu("XGame/Map/EntityBehaviour")]
    public class EntityBehaviour : MonoBehaviour
    {
        /// <summary>
        /// 序列化器
        /// </summary>
        [SerializeField]
        private ObjectCollector _collector = new ObjectCollector();

        /// <summary>
        /// 序列化器
        /// </summary>
        public IObjectCollector Collector => _collector;
    }
}