using FL.Battle.Components;
using FL.Battle.Components.AI;
using UnityEngine;
using XGame.Framework.Map;
using XGame.Framework.ObjectCollection;

namespace FL.Map
{
    public class AOEEntityView : SimpleEntityView<AOEEntityVM>, IAOEEntityAIContext, IVfxContext
    {
        public AOEEntityAI AI => GetComponent<AOEEntityAI>();
        public VfxComponent Vfx => GetComponent<VfxComponent>();

        //Transform IAOEEntityAIContext.ParticleTr => VM.ParticleRoot.transform;
        Transform IAOEEntityAIContext.Tr => VM.Tr;
        #region IVfxContext
        Transform IVfxContext.WorldTr => null;
        Transform IVfxContext.CenterTr => VM.Tr;
        Transform IVfxContext.CastTr => VM.Tr;
        #endregion
    }
    public class AOEEntityVM : EntityViewModel
    {
        //public GameObject ParticleRoot { get; private set; }
        protected override void OnInit(IObjectCollector collector)
        {
            //ParticleRoot = collector.GetGameObject("ParticleRoot");
        }
    }
}
