using FL.Battle.Components;
using FL.Battle.Components.AI;
using UnityEngine;
using XGame.Framework.Map;
using XGame.Framework.ObjectCollection;

namespace FL.Map
{
    /// <summary>
    /// 子弹实例
    /// </summary>
    public class BulletEntityView : SimpleEntityView<BulletEntityVM>, IVfxContext, IBulletAIContext
    {
        public BulletAI AI => GetComponent<BulletAI>();
        public VfxComponent Vfx => GetComponent<VfxComponent>();
        #region IVfxContext
        Transform IVfxContext.WorldTr => null;
        Transform IVfxContext.CenterTr => VM.Tr;
        Transform IVfxContext.CastTr => VM.Tr;
        #endregion
    }
    public class BulletEntityVM : EntityViewModel
    {
        //public Transform ActionRoot { get; private set; }
        protected override void OnInit(IObjectCollector collector)
        {
            //ActionRoot = collector.GetGameObject("ActionRoot").transform;
        }
    }
}
